/**
 * Primary Product Data Module - Core Product Categories
 * 
 * Contains primary product categories: Limpieza, Desinfección, and Salud-Bienestar.
 * These are the core product lines for the Ninu Factory Control system.
 * 
 * @fileoverview Primary product categories data
 * @module ProductDataPrimary
 */

import { Product } from '../types'

export const primaryProducts: Product[] = [
  // LIMPIEZA CATEGORY
  {
    id: 'prod-001',
    name: 'Jabón Líquido Para Trastes Ninu',
    category: 'limpieza',
    description: 'Jabón líquido concentrado para trastes con poder desengrasante superior',
    size: 4,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Tensioactivos biodegradables', 'Agentes desengrasantes', 'Fragrancia cítrica', 'Agua purificada'],
    useCase: ['Cocina', 'Trastes', 'Utensilios', 'Cristalería'],
    shelfLife: 24,
    currentStock: 250,
    minStock: 80,
    productionCost: 45.00,
    salePrice: 152.00,
    urgencyIndicators: {
      bestSeller: true,
      dailyPurchases: 23,
      showPopularityBadge: true,
      demandLevel: 'high'
    }
  },
  {
    id: 'prod-002',
    name: 'Jabón Líquido Hipoalergénico Para Ropa Ninu',
    category: 'limpieza',
    description: 'Jabón líquido hipoalergénico especial para ropa delicada y piel sensible',
    size: 5,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Tensioactivos suaves', 'Enzimas naturales', 'Acondicionadores de tela', 'Sin colorantes'],
    useCase: ['Ropa delicada', 'Bebés', 'Piel sensible', 'Lavandería'],
    shelfLife: 36,
    currentStock: 180,
    minStock: 60,
    productionCost: 85.00,
    salePrice: 164.50,
    urgencyIndicators: {
      isNewProduct: true,
      showNewBadge: true,
      launchDate: '2024-11-01',
      recommendedProduct: true,
      demandLevel: 'medium'
    }
  },
  {
    id: 'prod-003',
    name: 'Jabón Líquido Para Ropa Blanca Ninu',
    category: 'limpieza',
    description: 'Jabón líquido especializado para mantener el blanco brillante en prendas blancas',
    size: 5,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Tensioactivos blanqueadores', 'Enzimas proteolíticas', 'Agentes blanqueadores ópticos', 'Fragrancia fresca'],
    useCase: ['Ropa blanca', 'Uniformes', 'Sábanas', 'Textiles blancos'],
    shelfLife: 36,
    currentStock: 130,
    minStock: 45,
    productionCost: 82.00,
    salePrice: 164.50
  },
  {
    id: 'prod-004',
    name: 'Jabón Líquido Para Ropa Oscura Ninu',
    category: 'limpieza',
    description: 'Jabón líquido especializado para preservar colores oscuros y evitar decoloración',
    size: 5,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Tensioactivos protectores de color', 'Enzimas suaves', 'Agentes fijadores', 'Sin blanqueadores'],
    useCase: ['Ropa oscura', 'Jeans', 'Uniformes oscuros', 'Textiles de color'],
    shelfLife: 36,
    currentStock: 110,
    minStock: 40,
    productionCost: 83.00,
    salePrice: 164.50
  },
  {
    id: 'prod-005',
    name: 'Jabón Antibacterial Para Manos Ninu',
    category: 'limpieza',
    description: 'Jabón líquido antibacterial para higiene de manos con protección completa',
    size: 5,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Tensioactivos suaves', 'Agentes antibacteriales', 'Glicerina hidratante', 'Vitamina E'],
    useCase: ['Higiene personal', 'Hospitales', 'Oficinas', 'Restaurantes'],
    shelfLife: 24,
    currentStock: 200,
    minStock: 70,
    productionCost: 48.00,
    salePrice: 95.00,
    urgencyIndicators: {
      trendingProduct: true,
      dailyPurchases: 45,
      weeklyPurchases: 280,
      showPopularityBadge: true,
      demandLevel: 'very_high',
      exclusiveOffer: true
    }
  },
  {
    id: 'prod-006',
    name: 'Jabón Antibacterial Para Manos Ninu 500ml',
    category: 'limpieza',
    description: 'Presentación personal de jabón antibacterial para manos',
    size: 500,
    unit: 'ml',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Tensioactivos suaves', 'Agentes antibacteriales', 'Glicerina', 'Aloe vera'],
    useCase: ['Uso personal', 'Hogar', 'Oficina', 'Viajes'],
    shelfLife: 24,
    currentStock: 350,
    minStock: 100,
    productionCost: 15.00,
    salePrice: 60.21
  },
  {
    id: 'prod-007',
    name: 'Suavizante De Telas Ropa Blanca Ninu',
    category: 'limpieza',
    description: 'Suavizante especializado para ropa blanca con fragancia duradera',
    size: 5,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Compuestos suavizantes', 'Fragrancia floral', 'Agentes antiestaticos', 'Agua purificada'],
    useCase: ['Ropa blanca', 'Toallas', 'Sábanas', 'Textiles delicados'],
    shelfLife: 36,
    currentStock: 160,
    minStock: 55,
    productionCost: 65.00,
    salePrice: 139.19
  },
  {
    id: 'prod-008',
    name: 'Blanqueador Cloro En Gel Ninu 4L',
    category: 'limpieza',
    description: 'Blanqueador en gel con alta concentración de hipoclorito de sodio',
    size: 4,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Hipoclorito de sodio', 'Estabilizantes', 'Espesantes', 'Agua purificada'],
    useCase: ['Blanqueado', 'Desinfección', 'Manchas difíciles', 'Limpieza profunda'],
    shelfLife: 12,
    currentStock: 8,
    minStock: 40,
    productionCost: 58.00,
    salePrice: 119.90,
    urgencyIndicators: {
      lowStockThreshold: 10,
      showLowStockWarning: true,
      isOnSale: true,
      salePercentage: 25,
      saleEndDate: '2024-12-31',
      limitedTimeOffer: true,
      offerEndDate: '2024-12-31',
      demandLevel: 'high'
    }
  },
  {
    id: 'prod-009',
    name: 'Blanqueador Cloro En Gel Ninu 10L',
    category: 'limpieza',
    description: 'Blanqueador en gel presentación industrial con 99% efectividad',
    size: 10,
    unit: 'l',
    packaging: 'container',
    cofepisApproval: true,
    ingredients: ['Hipoclorito de sodio alta concentración', 'Estabilizantes', 'Espesantes industriales'],
    useCase: ['Uso industrial', 'Lavanderías', 'Hospitales', 'Hoteles'],
    shelfLife: 12,
    currentStock: 75,
    minStock: 25,
    productionCost: 115.00,
    salePrice: 236.90
  },
  {
    id: 'prod-010',
    name: 'Limpiador Multiusos Antibacterial Ninu',
    category: 'limpieza',
    description: 'Limpiador multiusos con acción antibacterial para todo tipo de superficies',
    size: 1,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Tensioactivos no iónicos', 'Agentes antibacteriales', 'Fragrancia lavanda', 'Agua tratada'],
    useCase: ['Cocina', 'Baño', 'Pisos', 'Muebles', 'Ventanas'],
    shelfLife: 24,
    currentStock: 280,
    minStock: 90,
    productionCost: 28.00,
    salePrice: 59.90,
    urgencyIndicators: {
      bestSeller: true,
      dailyPurchases: 67,
      weeklyPurchases: 420,
      showPopularityBadge: true,
      recommendedProduct: true,
      demandLevel: 'very_high'
    }
  },

  // DESINFECCIÓN CATEGORY
  {
    id: 'prod-011',
    name: 'Gel Antibacterial 1L con Dosificador Ninu',
    category: 'desinfeccion',
    description: 'Gel antibacterial 70% alcohol con dosificador, elimina 99.99% virus, bacterias y gérmenes',
    size: 1,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    cofepisRegistration: '0419C2020 SSA',
    ingredients: ['Alcohol etílico 70%', 'Glicerina', 'Carbómero', 'Agua purificada', 'Sin parabenos'],
    useCase: ['Higiene personal', 'Oficinas', 'Comercios', 'Transporte'],
    shelfLife: 24,
    currentStock: 400,
    minStock: 120,
    productionCost: 32.00,
    salePrice: 63.99,
    alcoholContent: 70,
    urgencyIndicators: {
      trendingProduct: true,
      dailyPurchases: 89,
      weeklyPurchases: 620,
      showPopularityBadge: true,
      isOnSale: true,
      salePercentage: 15,
      saleEndDate: '2024-12-25',
      demandLevel: 'very_high'
    }
  },
  {
    id: 'prod-012',
    name: 'Gel Antibacterial 5L Garrafa Premium Ninu',
    category: 'desinfeccion',
    description: 'Gel antibacterial calidad premium en presentación garrafa de 5 litros',
    size: 5,
    unit: 'l',
    packaging: 'container',
    cofepisApproval: true,
    cofepisRegistration: '0419C2020 SSA',
    ingredients: ['Alcohol etílico 70%', 'Glicerina', 'Carbómero', 'Aloe vera', 'Vitamina E'],
    useCase: ['Uso institucional', 'Escuelas', 'Hospitales', 'Oficinas'],
    shelfLife: 24,
    currentStock: 180,
    minStock: 60,
    productionCost: 135.00,
    salePrice: 275.00,
    alcoholContent: 70
  },
  {
    id: 'prod-013',
    name: 'Gel Antibacterial 20L Garrafa Industrial Ninu',
    category: 'desinfeccion',
    description: 'Gel antibacterial presentación industrial para mayoristas y distribuidores',
    size: 20,
    unit: 'l',
    packaging: 'container',
    cofepisApproval: true,
    cofepisRegistration: '0419C2020 SSA',
    ingredients: ['Alcohol etílico 70%', 'Glicerina', 'Carbómero', 'Conservadores naturales'],
    useCase: ['Mayoreo', 'Distribución', 'Industria', 'Instituciones grandes'],
    shelfLife: 24,
    currentStock: 85,
    minStock: 30,
    productionCost: 420.00,
    salePrice: 850.00,
    alcoholContent: 70
  },
  {
    id: 'prod-014',
    name: 'Gel Antibacterial Triple Desinfectante Ninu',
    category: 'desinfeccion',
    description: 'Gel antibacterial con fórmula triple desinfectante potenciada',
    size: 1,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    cofepisRegistration: '0419C2020 SSA',
    ingredients: ['Alcohol etílico 70%', 'Compuestos cuaternarios', 'Glicerina', 'Aloe vera natural'],
    useCase: ['Áreas médicas', 'Laboratorios', 'Clínicas', 'Uso especializado'],
    shelfLife: 24,
    currentStock: 150,
    minStock: 50,
    productionCost: 38.00,
    salePrice: 68.99,
    alcoholContent: 70
  },
  {
    id: 'prod-015',
    name: 'Sanitizante Líquido Multiusos Sales Cuaternarias Ninu',
    category: 'desinfeccion',
    description: 'Sanitizante líquido multiusos con sales cuaternarias 5ta generación, libre de alcohol',
    size: 1,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    cofepisRegistration: '2667C2018SSA',
    ingredients: ['Sales cuaternarias 0.18%', 'Agua purificada', 'Estabilizantes', 'Sin alcohol'],
    useCase: ['Superficies', 'Ambientes', 'Mascotas', 'Áreas sensibles'],
    shelfLife: 24,
    currentStock: 320,
    minStock: 100,
    productionCost: 18.00,
    salePrice: 24.00,
    quaternaryAmmoniumContent: 0.18
  },
  {
    id: 'prod-016',
    name: 'Sanitizante Líquido Sales Cuaternarias 5L Ninu',
    category: 'desinfeccion',
    description: 'Sanitizante líquido profesional con sales cuaternarias presentación 5L',
    size: 5,
    unit: 'l',
    packaging: 'container',
    cofepisApproval: true,
    cofepisRegistration: '2667C2018SSA',
    ingredients: ['Sales cuaternarias 0.18%', 'Agua purificada', 'Biodegradable', 'Pet-safe'],
    useCase: ['Uso profesional', 'Veterinarias', 'Guarderías', 'Espacios cerrados'],
    shelfLife: 24,
    currentStock: 140,
    minStock: 45,
    productionCost: 82.00,
    salePrice: 165.00,
    quaternaryAmmoniumContent: 0.18
  },
  {
    id: 'prod-017',
    name: 'Sanitizante Líquido Sales Cuaternarias 20L Ninu',
    category: 'desinfeccion',
    description: 'Sanitizante líquido industrial con sales cuaternarias para distribución',
    size: 20,
    unit: 'l',
    packaging: 'container',
    cofepisApproval: true,
    cofepisRegistration: '2667C2018SSA',
    ingredients: ['Sales cuaternarias 0.18%', 'Agua desionizada', 'Estabilizantes industriales'],
    useCase: ['Distribución', 'Industria alimentaria', 'Hospitales', 'Mayoreo'],
    shelfLife: 24,
    currentStock: 60,
    minStock: 20,
    productionCost: 245.00,
    salePrice: 298.99,
    quaternaryAmmoniumContent: 0.18
  },
  {
    id: 'prod-018',
    name: 'Kit Sanitizante Personal Escolar 60ml Ninu',
    category: 'desinfeccion',
    description: 'Kit sanitizante personal para estudiantes con fragancias variadas',
    size: 60,
    unit: 'ml',
    packaging: 'kit',
    cofepisApproval: true,
    cofepisRegistration: '0419C2020 SSA',
    ingredients: ['Alcohol etílico 70%', 'Glicerina', 'Fragancias naturales', 'Vitamina E'],
    useCase: ['Estudiantes', 'Escuelas', 'Uso personal', 'Niños'],
    shelfLife: 24,
    currentStock: 500,
    minStock: 150,
    productionCost: 8.00,
    salePrice: 25.00,
    alcoholContent: 70
  },

  // SALUD-BIENESTAR CATEGORY
  {
    id: 'prod-019',
    name: 'Gel Conductor Ultrasonido Electroestimulador Ninu',
    category: 'salud-bienestar',
    description: 'Gel conductor profesional para equipos de ultrasonido y electroestimulación',
    size: 1,
    unit: 'l',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Glicerina', 'Carboximetilcelulosa', 'Agua desionizada', 'Conservadores'],
    useCase: ['Ultrasonido', 'Electroestimulación', 'Fisioterapia', 'Uso médico'],
    shelfLife: 24,
    currentStock: 120,
    minStock: 40,
    productionCost: 95.00,
    salePrice: 169.90
  },
  {
    id: 'prod-020',
    name: 'Piedra Alumbre Desodorante Líquido Natural Ninu',
    category: 'salud-bienestar',
    description: 'Desodorante líquido natural a base de piedra alumbre, sin alcohol ni parabenos',
    size: 125,
    unit: 'ml',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Sulfato de aluminio y potasio', 'Agua purificada', 'Glicerina vegetal', 'Extractos naturales'],
    useCase: ['Higiene personal', 'Desodorante natural', 'Piel sensible', 'Uso diario'],
    shelfLife: 36,
    currentStock: 400,
    minStock: 120,
    productionCost: 25.00,
    salePrice: 49.90
  },
  {
    id: 'prod-021',
    name: 'Aceite Para Masaje Relajante Ninu',
    category: 'salud-bienestar',
    description: 'Aceite de masaje relajante para alivio del dolor muscular y relajación',
    size: 250,
    unit: 'ml',
    packaging: 'bottle',
    cofepisApproval: true,
    ingredients: ['Aceites esenciales', 'Aceite de almendras', 'Vitamina E', 'Extractos relajantes'],
    useCase: ['Masaje relajante', 'Dolor muscular', 'Hidratación', 'Bienestar'],
    shelfLife: 36,
    currentStock: 180,
    minStock: 60,
    productionCost: 45.00,
    salePrice: 89.90
  }
]